mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('workeu.urls')),
]

workeu/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^techwork/$', views.techwork, name='techwork'), # Переадресация на страницу технических работ
    url(r'^$', views.landing, name='landing'), # Переадресация для вывода Лендинга
    url(r'^post_list/$', views.post_list, name='post_list'), # ... для вывода страницы постов по Польше
	url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'), # ... для более детального вывода поста по Польше
	url(r'^contactView/$', views.contactView, name='contactView'), # ... для контактной формы
	url(r'^thanks/$', views.thanks, name='thanks'), # ... для страницы подтверждения отправки сообщения
	url(r'^postp_list_pribaltik/$', views.postp_list_pribaltik, name='postp_list_pribaltik'), # ... для вывода страницы постов по Польше
	url(r'^postp_detail_pribaltik/(?P<pk>[0-9]+)/$', views.postp_detail_pribaltik, name='postp_detail_pribaltik'), # ... для более детального вывода поста по Прибалтике
	url(r'^postf_list_finland/$', views.postf_list_finland, name='postf_list_finland'), # ... для вывода страницы постов по Польше
	url(r'^postf_detail_finland/(?P<pk>[0-9]+)/$', views.postf_detail_finland, name='postf_detail_finland'), # ... для более детального вывода поста по Прибалтике
	url(r'^alljobs/$', views.alljobs, name='alljobs'), # страница со всеми вакансиями 
    url(r'^resume/$', views.resume, name='resume'), # страница с резюме	
	url(r'^HelpInVisa/$', views.HelpInVisa, name='HelpInVisa'), # страница с визой
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #прибавим функцию static() для вывода фото

workeu/models.py
from django.db import models
from django.utils import timezone




class Post(models.Model): # Посты по Польше
    photo = models.ImageField("фотография", upload_to="workeu/media/photos/poland", default="", blank=True)
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)
		

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title
	

class Postp(models.Model): # Посты по Прибалтике
    photo = models.ImageField("фотография", upload_to="workeu/media/photos/pribaltik", default="", blank=True)
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)
		

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title	
		
class Postf(models.Model): # Посты по Финляндии
    photo = models.ImageField("фотография", upload_to="workeu/media/photos/finland", default="", blank=True)
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)
		

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title		

workeu/views.py
from django.utils import timezone
from .models import Post
from .models import Postp
from .models import Postf
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.core.mail import send_mail, BadHeaderError
from django import forms



# ПОЛЬША
# Лендинговая страница по краткому выводу постов по Польше
def landing(request):
    postsp = Postp.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')[0:10] #Ограничиваем вывод постов в Таллинне на главной странице
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')[0:10] #Ограничиваем вывод постов в Польше на главной странице
    postsf = Postf.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')[0:10] #Ограничиваем вывод постов в Финляндии на главной странице
    return render(request, 'workeu/landing.html', {'posts': posts, 'postsp': postsp, 'postsf': postsf})
	

def post_list(request): # Страница вывода постов по Польше
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    return render(request, 'workeu/post_list.html', {'posts': posts})
	
	
def post_detail(request, pk): # Страница вывода поста по Польше более детально
        post = get_object_or_404(Post, pk=pk)
        return render(request, 'workeu/post_detail.html', {'post': post})

def techwork(request): # Страница вывода сообщения о выполнении технических работ
            return render(request, 'workeu/techwork.html')		

#Контактная форма для отправки сообщения		
class ContactForm(forms.Form):
	subject = forms.CharField(max_length=100,widget=forms.TextInput(attrs={'size':'40','class': 'form-control'}))#Заполняем в скобках, чтобы тема работала в бутрстраповских стилях
	sender = forms.EmailField(widget=forms.TextInput(attrs={'size':'40','class': 'form-control'}))#Заполняем в скобках, чтобы тема работала в бутрстраповских стилях
	message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))#Заполняем в скобках, чтобы тема работала в бутрстраповских стилях
	copy = forms.BooleanField(required = False)

	
def contactView(request):
	if request.method == 'POST':
		form = ContactForm(request.POST)
		#Если форма заполнена корректно, сохраняем все введённые пользователем значения
		if form.is_valid():
			subject = form.cleaned_data['subject']
			sender = form.cleaned_data['sender']
			message = form.cleaned_data['message']
			copy = form.cleaned_data['copy']
            
			recipients = ['tzvanguardia@gmail.com']
			#Если пользователь захотел получить копию себе, добавляем его в список получателей
			if copy:
				recipients.append(sender)
			try:
				send_mail(subject, message, 'tzvanguardia@gmail.com', recipients)
			except BadHeaderError: #Защита от уязвимости
				return HttpResponse('Invalid header found')
			#Переходим на другую страницу, если сообщение отправлено
			return render(request, 'workeu/thanks.html')
	else:
		#Заполняем форму
		form = ContactForm()
	#Отправляем форму на страницу
	return render(request, 'workeu/contactView.html', {'form': form})
	
def thanks(reguest): # Страница вывода сообщения об отправке сообщения
    thanks = 'thanks'
    return render(reguest, 'workeu/thanks.html', {'thanks': thanks})	
	
# ПРИБАЛТИКА
def postp_list_pribaltik(request): # Страница вывода постов по Таллинну
    postsp = Postp.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    return render(request, 'workeu/postp_list_pribaltik.html', {'postsp': postsp})
	
	
def postp_detail_pribaltik(request, pk): # Страница вывода поста по Таллинну более детально
        post = get_object_or_404(Postp, pk=pk)
        return render(request, 'workeu/postp_detail_pribaltik.html', {'post': post})

# ФИНЛЯНДИЯ
def postf_list_finland(request): # Страница вывода постов по Финляндии
    postsf = Postf.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    return render(request, 'workeu/postf_list_finland.html', {'postsf': postsf})
	
	
def postf_detail_finland(request, pk): # Страница вывода поста по Финляндии более детально
        post = get_object_or_404(Postf, pk=pk)
        return render(request, 'workeu/postf_detail_finland.html', {'post': post})	

def alljobs(request):
    postsp = Postp.objects.filter(published_date__lte=timezone.now()).order_by('-published_date') #Вывод списка вакансий в Таллине
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date') #Вывод списка вакансий в Польше
    postsf = Postf.objects.filter(published_date__lte=timezone.now()).order_by('-published_date') #Вывод списка вакансий в Финляндии
    return render(request, 'workeu/alljobs.html', {'posts': posts, 'postsp': postsp, 'postsf': postsf})		
	
def resume(reguest): # Страница вывода сообщения об отправке сообщения
    return render(reguest, 'workeu/resume.html')

def HelpInVisa(reguest): # Страница с визой
    return render(reguest, 'workeu/HelpInVisa.html')		

workeu/templates/workeu/HelpInVisa.html
{% extends 'workeu/base.html' %}
{% load staticfiles %}

{% block content %}

<div class="row centered">
    <div class="col-lg-10 col-lg-offset-1 col-lg-offset-1">
	
						  
							    <h1>Помощь при получении рабочей визы</h1>
							
<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Окажем помощь</th>
      <th>Вы можете сделать самостоятельно</th>
      </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">Загранпаспорт</th>
      <td></td>
      <td>Для получения заграничного паспорта Вы можете обратиться в ОВИР или в паспортный сервис</td>
      
    </tr>
    <tr>
      <th scope="row">Приглашение</th>
      <td>Мы поможем Вам получить официальное приглашение от работодателя в короткий срок и без затрат времени и сил с Вашей стороны.
          Работодателю нужно достаточно много времени чтобы зарегистрировать приглашение в местной администрации – 
		  есть приемные и не приёмные дни и часы, затем нужно найти время и возможность передать это приглашение в Украину. 
		  Мы избавим Вас от волнений и долгих ожиданий.</td>
      <td>Процесс получения рабочей визы начинается с получения официального приглашения от работодателя. Вы можете самостоятельно в 
	      интернете найти интересующие Вас вакансии на сайтах прямых работодателей и, выслав свое резюме и получив подтверждение 
		  от работодателя что Вы будете приняты им на работу, созвониться с ним и получить от него официальное приглашение 
		  (по польскому законодательству приглашение делается до 14 дней + время для передачи вам оригинала приглашения). 
		  Для этого работодатель должен быть согласен подождать Вас как работника около полутора месяцев, пока будет оформляться 
		  Ваша рабочая виза.</td>
      
    </tr>
    <tr>
      <th scope="row">Визовый сбор</th>
      <td>Мы подскажем где находится визовый центр Польши, в каком банке нужно заплатить, какие документы нужно заполнить, 
	      на что обратить внимание и обязательно проверить</td>
      <td>Оплачиваете визовый сбор 18 евро.</td>
      
    </tr>
	 <tr>
      <th scope="row">Страховка</th>
      <td>Мы имеем право оформлять страховку от имени  "ПЗУ Украина".</td>
      <td>Вы можете самостоятельно оформить страховой медицинский полис в страховой компании.</td>
      
    </tr>
	<tr>
      <th scope="row">Заполнить анкету</th>
      <td>Мы заполним за Вас Анкету в Визовый Центр (поскольку от правильности заполнения Анкеты зависит решение Визового Центра выдать 
	      или не выдать Вам визу – желательно, чтобы это делали люди, которые занимаются этим не первый день), 
		  проверим наличие всех необходимых документов.</td>
      <td>Имея на руках оригинал (обязательно ОРИГИНАЛ) приглашения, квитанции об оплате визового сбора – можете попробовать самостоятельно 
	      заполнить Анкету для Визового Центра и собрать все необходимые документы для подачи в визовый центр 
		  </td>
      
    </tr>
	<tr>
      <th scope="row">Записаться на подачу в визовый центр</th>
      <td>Если Вы хотите как можно быстрее получить визу - мы сможем записать Вас на ближайшую свободную дату для подачи документов в 
	      Визовый Центр.</td>
      <td>В случае, если документы подаются в Визовый Центр, который принимает их к рассмотрению строго по предварительной записи, 
	      необходимо назначить дату и время подачи. (Некоторые Визовые Центры принимают только в определённые дни и очереди расписаны на 
		  несколько месяцев вперед).</td>
      
    </tr>
	<tr>
      <th scope="row">Подать документы в визовый центр</th>
      <td>Наш менеджер отправит Вам подготовленные документы, которые Вам нужно отнести в визовый центр, подробно проконсультирует и 
	      Вам останется, только сдать их.</td>
      <td>В назначенное время прийти в Визовый Центр с пакетом необходимых документов. В Визовом Центре Вас встретит работник, имеющий 
	      перечень заявителей, зарегистрированных на подачу документов в этот день. При предъявлении загранпаспорта, на который была 
		  осуществлена запись, сотрудник пропустит Вас и выдаст талон на электронную очередь. В порядке электронной очереди Вы пройдете 
		  к окну приема документов и, после предварительной их проверки, у Вас их примут.</td>
      
    </tr>
	<tr>
      <th scope="row">Подобрать вакансию</th>
      <td>И снова время и силы. Если Вы предоставите нам возможность помочь Вам в подборе вакансии – Ваша задача только прислать нам свое 
	      резюме в развернутом виде. Мы переводим Ваше резюме на язык работодателей, рассылаем его в несколько предприятий, проводим переговоры 
	      с работодателями для получения лучших условий труда и лучшей заработной платы (в зависимости от Вашей квалификации и опыта работы) 
	      и в итоге даём на Ваше рассмотрение несколько вакансий, по которым Вам предлагают лучшие условия.</td>
      <td>Когда виза уже у Вас на руках – теперь как раз самое время подобрать себе работу. В сети интернет очень много предложений, 
	      Вы можете попробовать сами сориентироваться в этом многообразии вакансий. Ваша задача – составить развернутое резюме, которое 
		  заинтересует работодателя, отправить его предполагаемому работодателю и ждать ответ. Проблема может состоять в том, что 
		  резюме нужно составлять на языке работодателя. И когда рассмотрят Ваше резюме – тоже не известно.</td>
      
    </tr>
	<tr>
      <th scope="row">Дорога до места работы</th>
      <td>Есть еще одна часть действий для того, чтобы Вы уже могли приступить к работе – дорога до работодателя.
          В зависимости от Вашего региона проживания мы Вам поможем составить маршрут передвижения до нужного Вам города, 
		  купить билеты по более дешевой цене, предоставить встречающего в городе предполагаемой работы и сопровождение при поселении и 
		  оформлении Вас на новом рабочем месте, а также проведем консультацию по правилам пересечения границы.</td>
      <td>Если вы справились со всеми вышеупомянутыми пунктами и получили подтверждение от работодателя что Вы подходите на интересующую Вас 
	      вакансию и он Вас ждет в определенный день для трудоустройства, осталось чуть-чуть – добраться до места работы. Вам нужно приобрести 
	      билеты, собрать все необходимые вещи и самое главное - пересечь границу, правильно отвечая на вопросы пограничников.</td>
      
    </tr>
	<tr>
      <th scope="row">Стоимость</th>
      <td>140€ + страховка.</td>
      <td>Только стоимость страховки.</td>
      
    </tr>
  </tbody>
</table>
<h3 class="glyphicon glyphicon-share"><a class="g" href="{% url 'landing' %}">На главную</a></h3><br>
    </div>
</div>
{% endblock %}

workeu/templates/workeu/alljobs.html
{% extends 'workeu/base.html' %}




{% block content %} 

     <div class="row centered">
					    <br>
						    <div class="col-lg-12">
							    <h1>Все доступные вакансии</h1>
							</div>
	 </div>	
	 
               <div class="container w paddingtop">
				    <div class="row centered">
					    <br><br>
						    <div class="col-lg-4">
							    
								<span class="topikalljobs"><a class="g" href="{% url 'post_list' %}">Вакансии в Польше</a></span>
								<p>
								    {% for post in posts %}
									    
										 <div class="{% cycle 'row3' 'row4' %}"> <!-- Чередование стилей. В данном случае цвета -->
                                             <div class="col-4 tilleLanding"><a href="{% url 'post_detail' pk=post.pk %}">&nbsp;{{ post.title }}</a></div>
										   
										 </div>
                                           
										  	 
					                    
                                    {% endfor %} 
								</p>
							</div>
							<div class="col-lg-4">
							    
								<span class="topikalljobs"><a class="g" href="{% url 'postp_list_pribaltik' %}">Вакансии в Прибалтике</a></span>
								<p>
								
								   {% for post in postsp %}
									    
										 <div class="{% cycle 'row3' 'row4' %}"> <!-- Чередование стилей. В данном случае цвета -->
                                             <div class="col-4 tilleLanding"><a href="{% url 'postp_detail_pribaltik' pk=post.pk %}">&nbsp;{{ post.title }}</a></div>
										   
										 </div>
                                           
										  	 
					                    
                                    {% endfor %} 
							  
								</p>
							</div>
							<div class="col-lg-4">
							    
								<span class="topikalljobs"><a class="g" href="{% url 'postf_list_finland' %}">Вакансии в Финляндии</a></span>
								<p>
								    {% for post in postsf %}
									    
										 <div class="{% cycle 'row3' 'row4' %}"> <!-- Чередование стилей. В данном случае цвета -->
                                             <div class="col-4 tilleLanding"><a href="{% url 'postf_detail_finland' pk=post.pk %}">&nbsp;{{ post.title }}</a></div>
										   
										 </div>
                                           
										  	 
					                    
                                    {% endfor %} 
								</p>
							</div>
							
					</div>
					<br><br>
				</div>
				<br><hr><!-- Secondary, outline button -->
					<div class="container">
					    <div class="row centered">
                    <div class="col-lg-12"><h3 class="glyphicon glyphicon-share"><a class="g" href="{% url 'landing' %}">На главную</a></h3><br></div>
					    </div>
					</div><br>
				
{% endblock content %}	

workeu/templates/workeu/base.html
{% load staticfiles %}
<html>
<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EU</title>
	<!-- Bootstrap -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
	<link rel="stylesheet" href="{% static 'css/workeu.css' %}">
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,cyrillic" rel="stylesheet" type="text/css">
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="containernav">  
	    <div class="navbar-header">
		    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
			    <span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			
			    <a class="navbar-brand" href="{% url 'landing' %}"><i class="fa fa-university" aria-hidden="true">&nbsp;Working in Europe</i></a>
		</div>
		    <div class="navbar-collapse collapse right">
			    <ul class="nav navbar-nav navbar-right">
				   {% url 'landing' as url %}
				    <li {% if request.path == url %}class = "active"{% endif %}><a href="{{url}}">Главная</a></li>
										
					<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Вакансии<span class="caret"></span></a>
					    <ul class="dropdown-menu" role="menu">
						{% url 'post_list' as url %}
					        <li {% if request.path == url %}class = "active"{% endif %}><a href="{{url}}">Польша</a></li>
						{% url 'postp_list_pribaltik' as url %}	
							<li {% if request.path == url %}class = "active"{% endif %}><a href="{{url}}">Прибалтика</a></li>
						{% url 'postf_list_finland' as url %}	
							<li {% if request.path == url %}class = "active"{% endif %}><a href="{{url}}">Финляндия</a></li>
					    </ul>
					</li>
					{% url 'HelpInVisa' as url %}
                    <li {% if request.path == url %}class = "active"{% endif %}><a href="{{url}}">Помощь с визами</a></li>
					{% url 'techwork' as url %}
					<li {% if request.path == url %}class = "active"{% endif %}><a href="{{url}}">Новости</a></li>
				</ul>
			
			</div>
    </div>
</div>	
<a href="{% url 'contactView' %}" class="top-menu"><span class="knopkaPost btn btn-primary btn-lg active glyphicon glyphicon-envelope">&nbsp;Написать сообщение</span></a>
 

    
                {% block content %}
                {% endblock %}
		   

<div id="f">
    <div class="container">
	    <div class="row centered">
		<i class="fa fa-phone-square" aria-hidden="true">&nbsp;+380977447700&nbsp;&nbsp; +380734196070&nbsp;&nbsp; +380994439045</i><br>
		<hr></hr>
		 <div class="container">
					    <div class="row centered">
						    <div class="col-lg-6">
		                        <i class="fa fa-envelope fontLeft" aria-hidden="true">&nbsp;Предложения для сотрудничества:<br>tzvanguardia@gmail.com</i><br>
		                    </div>
							<div class="col-lg-6">
		                        <i class="fa fa-address-card fontLeft" aria-hidden="true">&nbsp;Юридический адрес:<br>г.Киев, ул. Тампере 13Б , офис 315</i><br>
		                    </div> 
		                </div>
						<hr></hr>
		</div>
		    <a href="#"><i class="fa fa-twitter"></i></a>
			<a href="#"><i class="fa fa-facebook"></i></a>
			<a href="#"><i class="fa fa-vk"></i></a>
		</div>
	</div>
</div>
	
	
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="{% static 'scripts/bootstrap.min.js' %}"></script>
</body>
</html>

workeu/templates/workeu/contactView.html
{% extends 'workeu/base.html' %}
{% load staticfiles %}

{% block content %}
<div class="content container">
<div class="row">
<div class="col-md-12">
<form action="/contactView/" method="post">{% csrf_token %}
{{ form.non_field_errors }}
<div>
<label for="id_subject">Тема (укажите интересующую Вас вакансию):</label>
{{ form.subject.errors }}
{{ form.subject }}
</div>
<div>
<label for="id_sender">E-mail:</label>
{{ form.sender.errors }}
{{ form.sender }}
</div>
<div>
<label for="id_message">Сообщение (вкратце опишите Ваш опыт и навыки):</label>
{{ form.message.errors }}
{{ form.message }}
</div>
<div>
{{ form.copy.errors }}
 <label for="id_copy">Отправить копию себе {{ form.copy }}</label>
</div>
<input class='elt' type="submit" value="Отправить"/><span class='sec-elt'><span class="btn-primary btn-lg active glyphicon glyphicon-envelope"</span></span>
</form>
</div>
<h3 class="glyphicon glyphicon-share centered"><a class="g" href="{% url 'landing' %}">На главную</a></h3><br>
</div>
</div>
{% endblock %}

workeu/templates/workeu/post_detail.html
  {% extends 'workeu/base.html' %}

    {% block content %}
	<div class="content container">
    <div class="row">
	<div class="col-md-12">
	<span class="topik"><a class="g" href="{% url 'post_list' %}">Вакансии в Польше&nbsp;<i class="fa fa-angle-double-right" aria-hidden="true"></i></a></span>
	</div>
	
    <div class="col-md-12">
        <div class="post">
		
		
		    
            {% if post.published_date %}
                <div class="date">
                    {{ post.published_date }}
					
					
                </div>
				<div class="fotoFloat">
				{% if post.photo %}
                    <img class="img-responsive img-rounded img-thumbnail" alt="{{post.photo}}" src="{{post.photo.url}}" />

                {% endif %}
				</div>
            {% endif %}
            <h2>{{ post.title }}</h2>
            <p>{{ post.text|linebreaksbr }}</p>
			
			<h3 class="glyphicon glyphicon-share"><a class="g" href="{% url 'landing' %}">На главную</a></h3><br> 
			<div class="col-lg-12"><button type="button" class="btn btn-success postresume btn-lg"><span class="buttall"><a href="{% url 'resume' %}">Заполнить анкету</a></span></button><br></div>
			
			<hr class="style-two"></hr>
        </div>
		</div>
		 
		
		
		</div>
        </div>		
		
    {% endblock %}
	
    
	
	

workeu/templates/workeu/post_list.html
{% extends 'workeu/base.html' %}

{% block content %} 
<div class="content container">
<div class="row">
<div class="col-md-12">
<span class="topik">Вакансии в Польше</span>
               		
	 		
<table class="table table-striped  post postList">
<tr>
 <th>Вакансия</th>
 <th>Дата публикации</th>
</tr>
<tbody>
  <div class="post postList">
 {% for post in posts %} 
<tr>
     
 <td>
     <h1 class="glyphicon glyphicon-share"><a class="block" href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
 </td>
<td>
     <div class="date">
		{{ post.published_date }}
	 </div>
</td>

</tr>
 {% endfor %}
</div>
</tbody>
</table>
				 
				
</div>	
</div>
</div>			
{% endblock content %}				
				
           
		

workeu/templates/workeu/postf_detail_finland.html
 {% extends 'workeu/base.html' %}

{% block content %}
	<div class="content container">
    <div class="row">
	<div class="col-md-12">
	    <span class="topik"><a class="g" href="{% url 'postf_list_finland' %}">Вакансии в Финляндии&nbsp;<i class="fa fa-angle-double-right" aria-hidden="true"></i></a></span>
	</div>
    <div class="col-md-12">
	
        <div class="post">
		
            {% if post.published_date %}
                <div class="date">
                    {{ post.published_date }}
                </div>
				<div class="fotoFloat">
				{% if post.photo %}
                    <img class="img-responsive img-rounded img-thumbnail" alt="{{post.photo}}" src="{{post.photo.url}}" />

                {% endif %}
				</div>
            {% endif %}
            <h2>{{ post.title }}</h2>
            <p>{{ post.text|linebreaksbr }}</p>
			<h3 class="glyphicon glyphicon-share"><a class="g" href="{% url 'landing' %}">На главную</a></h3><br>
			<div class="col-lg-12"><button type="button" class="btn btn-success postresume btn-lg"><span class="buttall"><a href="{% url 'resume' %}">Заполнить анкету</a></span></button><br></div>
			<hr class="style-two"></hr>
        </div>
		</div>
		</div>
        </div>		
		
{% endblock %}
	
    
	
	

workeu/templates/workeu/postf_list_finland.html
{% extends 'workeu/base.html' %}

{% block content %} 
<div class="content container">
<div class="row">
<div class="col-md-12">
<span class="topik">Вакансии в Финляндии</span>
                <table class="table table-striped  post postList">
<tr>
 <th>Вакансия</th>
 <th>Дата публикации</th>
</tr>
<tbody>
  <div class="post postList">
 {% for post in postsf %} 
<tr>
     
 <td>
     <h1 class="glyphicon glyphicon-share"><a class="block" href="{% url 'postf_detail_finland' pk=post.pk %}">{{ post.title }}</a></h1>
 </td>
<td>
     <div class="date">
		{{ post.published_date }}
	 </div>
</td>

</tr>
 {% endfor %}
</div>
</tbody>
</table>
				
				 
</div>	
</div>
</div>
		
{% endblock content %}				
				
           
		

workeu/templates/workeu/postp_list_pribaltik.html
{% extends 'workeu/base.html' %}

{% block content %} 
<div class="content container">
<div class="row">
<div class="col-md-12">
<span class="topik">Вакансии в Прибалтике</span>
                <table class="table table-striped  post postList">
<tr>
 <th>Вакансия</th>
 <th>Дата публикации</th>
</tr>
<tbody>
  <div class="post postList">
 {% for post in postsp %} 
<tr>
     
 <td>
     <h1 class="glyphicon glyphicon-share"><a class="block" href="{% url 'postp_detail_pribaltik' pk=post.pk %}">{{ post.title }}</a></h1>
 </td>
<td>
     <div class="date">
		{{ post.published_date }}
	 </div>
</td>

</tr>
 {% endfor %}
</div>
</tbody>
</table>
				
				 
</div>	
</div>
</div>
		
{% endblock content %}				
				
           
		